### ISSUE TITLE
New functionality request - change state after losing connection

### ISSUE THREAD

**Issue by Sufixx** [tschaban/SONOFF-firmware#25]
Hello,

I wish AFE had the following functionality settings:
When wifi or mqtt goes down for an extended period of time (amount of time to set), do:

Change state of relay to (selectable options): no change, turn off, turn on
There are already settings for changing state when MQTT connection is back, but imagine situation then for some reason wifi router or mqtt server dies, sonoff is left all alone and we're out of the home - heating/watering/A/C keeps running until we do return and may cause some problems or at least boil fish in aquarium if not equipped in own timer/themostat.

Greetings!

**Comment by tschaban** [comment]
hi, make sense. I added to a completly newer version of AFE firmware I'm working on
https://github.com/tschaban/AFE-Firmware/issues/29

**Comment by tschaban** [comment]
will be implemented in other AFE project
https://github.com/tschaban/AFE-Firmware

**Comment by Sufixx** [comment]
Thanks!

until new release I added Relay.off();  to runSleepMode for one of my switches  ;)
